# Fill in your actual Render values
spring.datasource.url=postgresql://blood_donation_db_3hie_user:UTYFaj5wPHQfdmhY0Bs5cQx9Mdk6bZHX@dpg-d85b8qreo5us73bc9fqg-a.singapore-postgres.render.com/blood_donation_db_3hie
spring.datasource.username=blood_donation_db_3hie_user
spring.datasource.password=UTYFaj5wPHQfdmhY0Bs5cQx9Mdk6bZHX
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

logging.level.com.bdms=INFO
logging.level.org.springframework.security=WARN